ingestion:
  url: https://github.com/lunarway/de-assignment/tree/master/data
  repo_url: https://github.com/lunarway/de-assignment/tree/master/
  sink: lake/bronze/
  user: lunarway
  repo: de-assignment
  batch_size: 500
  file_size: 104857600 # 100MB
  save_tree: False
  use_cached: False
  file_path: /artefacts/tree.pkl
  download_method: parallel
  use_api: False
transformation:
  source: data/
  #source: lake/bronze/data/
  sink: lake/gold/
